apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
spec:
  type: NodePort  
  selector:
    app: gitops-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
